# Generated by Django 5.2.5 on 2025-08-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المبني')),
                ('address', models.TextField(verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'مبني',
                'verbose_name_plural': 'المباني',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المستأجر')),
                ('tenant_type', models.CharField(choices=[('Individual', 'فرد'), ('Company', 'شركة')], max_length=20, verbose_name='نوع المستأجر')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('authorized_signatory', models.CharField(blank=True, help_text='يملا فقط في حال كان المستأجر شركة', max_length=150, null=True, verbose_name='المفوض بالتوقيع')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرين',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='رقم الوحدة')),
                ('unit_type', models.CharField(choices=[('Office', 'مكتب'), ('Apartment', 'شقة'), ('shop', 'محل')], max_length=20, verbose_name='نوع الوحدة')),
                ('floor', models.IntegerField(verbose_name='الطابق')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة الإيجار')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.building', verbose_name='المبني')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('contract_form_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم نموذج العقد')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الإيجار الشهري')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء العقد')),
                ('electricity_meter', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد الكهرباء')),
                ('water_meter', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد الماء')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired_soon', 'قريب الانتهاء'), ('expired', 'منتهي'), ('canceled', 'ملغي')], default='active', max_length=20, verbose_name='حالة العقد')),
                ('office_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='رسوم المكتب')),
                ('admin_fee', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='الرسوم الإدارة')),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='رسوم تسجيل العقد (٣٪\u061c)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tenant', verbose_name='المستأجر')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
            },
        ),
    ]
