# Generated by Django 5.2.5 on 2025-09-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tenant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('submitted', 'تم الإرسال'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='submitted', max_length=20, verbose_name='الحالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance_requests/', verbose_name='صورة مرفقة (اختياري)')),
                ('reported_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('staff_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الموظف')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='dashboard.lease', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-reported_date'],
            },
        ),
    ]
