# Generated by Django 5.2.5 on 2025-09-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'صيانة'), ('utilities', 'خدمات'), ('salaries', 'رواتب'), ('marketing', 'تسويق'), ('admin', 'رسوم إدارية/حكومية'), ('other', 'أخرى')], max_length=50, verbose_name='فئة المصروف')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('expense_date', models.DateField(verbose_name='تاريخ المصروف')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='إيصال/فاتورة(اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dashboard.building', verbose_name='المبني')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
            },
        ),
    ]
