# Generated by Django 5.2.5 on 2025-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('maintenance', 'صيانة'), ('utilities', 'خدمات (كهرباء، ماء، غاز)'), ('salaries', 'رواتب'), ('marketing', 'تسويق'), ('admin', 'رسوم إدارية/حكومية'), ('other', 'أخرى')], max_length=50, verbose_name='فئة المصروف'),
        ),
    ]
