# Generated by Django 5.2.5 on 2025-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_for_month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=None, verbose_name='دفعة عن شهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_for_year',
            field=models.IntegerField(default=2025, verbose_name='دفعة عن سنة'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('lease', 'payment_for_month', 'payment_for_year')},
        ),
    ]
