# Generated by Django 5.2.5 on 2025-09-17 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_payment_payment_for_month_payment_payment_for_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'مبنى', 'verbose_name_plural': 'المباني'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصاريف'},
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المبنى'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dashboard.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('maintenance', 'صيانة'), ('utilities', 'خدمات (كهرباء، ماء)'), ('salaries', 'رواتب'), ('marketing', 'تسويق'), ('admin', 'رسوم إدارية/حكومية'), ('other', 'أخرى')], max_length=50, verbose_name='فئة المصروف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='إيصال/فاتورة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='الرسوم الإدارية'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='رسوم تسجيل العقد (3%)'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('expiring_soon', 'قريب الانتهاء'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='active', editable=False, max_length=20, verbose_name='حالة العقد'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='water_meter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد المياه'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'تم الإرسال'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='submitted', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_for_month',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='دفعة عن شهر'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='authorized_signatory',
            field=models.CharField(blank=True, help_text='يُملأ فقط في حال كان المستأجر شركة', max_length=150, null=True, verbose_name='المفوض بالتوقيع'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], max_length=20, verbose_name='نوع المستأجر'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(blank=True, help_text='اربط المستأجر بحساب مستخدم لتسجيل الدخول إلى البوابة.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاحة للإيجار'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('office', 'مكتب'), ('apartment', 'شقة'), ('shop', 'محل')], max_length=20, verbose_name='نوع الوحدة'),
        ),
    ]
