# Generated by Django 5.2.5 on 2025-09-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_building_address_ar_building_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='staff_notes_ar',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='staff_notes_en',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='title_en',
        ),
    ]
