# Generated by Django 5.2.5 on 2025-09-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_maintenancerequest_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='الشعار')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للتواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name=' الهاتف للتواصل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'ملف الشركة',
                'verbose_name_plural': 'ملف الشركة',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القالب')),
                ('body', models.TextField(help_text='استخدم HTML لتخصيص القالب.', verbose_name='محتوى القالب')),
            ],
            options={
                'verbose_name': 'قالب عقد',
                'verbose_name_plural': 'قوالب العقود',
            },
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='building',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='authorized_signatory_ar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='authorized_signatory_en',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name_en',
        ),
        migrations.AddField(
            model_name='lease',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='lease',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='من 1 إلى 5 نجوم.', verbose_name='تقييم العميل'),
        ),
    ]
