# Generated by Django 5.2.5 on 2025-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_maintenancerequest_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='شركة إدارة الإيجارات', max_length=150, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='الشعار')),
                ('primary_color', models.CharField(default='#993333', help_text='مثال:#993333 ', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#D4Af37', help_text='مثال:#333399 ', max_length=7, verbose_name='اللون الثانوي')),
            ],
            options={
                'verbose_name': 'ملف الشركة',
                'verbose_name_plural': 'ملفات الشركة',
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'permissions': [('can_view_buildings_reports', 'يمكنه عرض تقارير المباني')], 'verbose_name': 'مبنى', 'verbose_name_plural': 'المباني'},
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'permissions': [('can_view_financial_summary', 'يمكنه عرض ملخص مالي')], 'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'permissions': [('can_view_tenant_portal', 'يمكنه عرض بوابة المستأجرين')], 'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرين'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='authorized_signatory_ar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='authorized_signatory_en',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name_en',
        ),
    ]
