# Generated by Django 5.2.5 on 2025-09-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_maintenancerequest_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='authorized_signatory_ar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='authorized_signatory_en',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name_en',
        ),
    ]
