# Generated by Django 5.2.5 on 2025-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_maintenancerequest_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
            ],
            options={
                'verbose_name': 'ملف الشركة',
                'verbose_name_plural': 'ملفات الشركة',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='building_logos/', verbose_name='شعار المبنى(اختياري)'),
        ),
    ]
