# Generated by Django 5.2.5 on 2025-09-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_building_address_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('commercial_registration', models.CharField(blank=True, max_length=100, verbose_name='رقم السجل التجاري')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'ملف الشركة',
                'verbose_name_plural': 'ملفات الشركة',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='amenties',
            field=models.TextField(blank=True, help_text='مفصولة بفاصلة، مثال: مكيف، واي فاي، غسالة، إلخ.', verbose_name='المرافق والمميزات'),
        ),
        migrations.AddField(
            model_name='unit',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المساحة(متر مربع)'),
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_images/', verbose_name='صورة الوحدة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.unit', verbose_name='الوحدة')),
            ],
        ),
    ]
