# Generated by Django 5.2.5 on 2025-09-25 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_company_alter_building_options_alter_lease_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='مرسل من'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='commercial_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='ملاحظات داخلية للموظفين فقط', null=True, verbose_name='ملاحظات داخلية'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='تقيم داخلي للعميل من 1 إلى 5 نجوم', verbose_name='تقيم العميل'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_card_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم البطاقة الضريبية'),
        ),
    ]
