# Generated by Django 5.2.7 on 2025-10-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_company_contracttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الشيك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشيك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقداً'), ('check', 'شيك'), ('bank_transfer', 'تحويل بنكي'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
