# Generated by Django 5.2.5 on 2025-09-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_companyprofile_unit_amenties_unit_area_unitimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitimage',
            options={'verbose_name': 'صورة الوحدة', 'verbose_name_plural': 'صور الوحدات'},
        ),
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات خاصة بالموظفين، غير مرئية للمستأجرين.', verbose_name='ملاحظات إدارية'),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'متاحة'), ('rented', 'موجرة'), ('maintenance', 'تحت الصيانة')], default='available', max_length=20, verbose_name='حالة الوحدة'),
        ),
    ]
