# Generated by Django 5.2.5 on 2025-09-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: عقد إيجار شقة', max_length=200, verbose_name='عنوان القالب')),
                ('body', models.TextField(help_text='استخدم المتغيرات التالية ليتم استبداله تلقائيا: {{tenant_name}}, {{ unit_full_address }}, {{ start_date }}, {{ end_date }}, {{ monthly_rent_amount }}, {{ monthly_rent_words }}, {{ contract_number }}.', verbose_name='محتوى القالب')),
            ],
            options={
                'verbose_name': 'قالب عقد',
                'verbose_name_plural': 'قوالب العقود',
            },
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'permissions': [('can_view_financial_summary', 'يمكنه عرض ملخص مالي'), ('canc_cancel_lease', 'يمكنه إلغاء عقد')], 'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
        migrations.AddField(
            model_name='lease',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='تجديد تلقائي عند الانتهاء'),
        ),
        migrations.AddField(
            model_name='lease',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='lease',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='lease',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.contracttemplate', verbose_name='قالب العقد المستخدم'),
        ),
    ]
