# Generated by Django 5.2.7 on 2025-10-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_payment_bank_name_payment_check_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address_ar',
            field=models.TextField(null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='building',
            name='address_en',
            field=models.TextField(null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم المبنى'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم المبنى'),
        ),
        migrations.AddField(
            model_name='expense',
            name='description_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='expense',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='authorized_signatory_ar',
            field=models.CharField(blank=True, help_text='يُملأ فقط في حال كان المستأجر شركة', max_length=150, null=True, verbose_name='المفوض بالتوقيع'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='authorized_signatory_en',
            field=models.CharField(blank=True, help_text='يُملأ فقط في حال كان المستأجر شركة', max_length=150, null=True, verbose_name='المفوض بالتوقيع'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='اسم المستأجر'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='اسم المستأجر'),
        ),
    ]
