# Generated by Django 5.2.7 on 2025-10-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_building_address_ar_building_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_status',
            field=models.CharField(blank=True, choices=[('pending', 'معلق - في الانتظار'), ('cashed', 'تم الصرف'), ('returned', 'مرتجع')], max_length=20, null=True, verbose_name='حالة الشيك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب إرجاع الشيك'),
        ),
    ]
