# Generated by Django 5.2.5 on 2025-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_contracttemplate_alter_lease_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'سند صرف (مصروف)', 'verbose_name_plural': 'سندات الصرف (المصروفات)'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'سند قبض (دفعة إيجار)', 'verbose_name_plural': 'سندات القبض (دفعات الإيجار)'},
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_to',
            field=models.CharField(default='', max_length=150, verbose_name='مدفوع إلى / المستفيد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='voucher_number',
            field=models.CharField(default='', editable=False, max_length=50, unique=True, verbose_name='رقم سند الصرف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_details',
            field=models.CharField(blank=True, help_text='يُملأ فقط في حال كانت طريقة الدفع شيك', max_length=150, null=True, verbose_name='تفاصيل الشيك/التحويل'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('online', 'دفع إلكتروني')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_number',
            field=models.CharField(default='', editable=False, max_length=50, unique=True, verbose_name='رقم سند القبض'),
            preserve_default=False,
        ),
    ]
