# Generated by Django 5.2.7 on 2025-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_payment_check_status_payment_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='check_status',
            field=models.CharField(blank=True, choices=[('pending', 'معلق - في الانتظار'), ('cashed', 'تم الصرف'), ('returned', 'مرتجع')], default='pending', max_length=20, null=True, verbose_name='حالة الشيك'),
        ),
    ]
