# Generated by Django 5.2.5 on 2025-09-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_expense_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='vacant_since',
            field=models.DateField(blank=True, null=True, verbose_name='شاغرة منذ تاريخ'),
        ),
    ]
