# Generated by Django 5.2.7 on 2025-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_payment_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_ar',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم الشركة'),
        ),
    ]
