# Generated by Django 5.2.7 on 2025-10-08 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_otp_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='الرجاء إدخال رقم هاتف عماني صالح يبدأ بـ +968 (8 أرقام بعد المقدمة)', regex='^\\+968\\d{8}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='رقم الهاتف للتحقق عبر OTP', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='الرجاء إدخال رقم هاتف عماني صالح يبدأ بـ +968 (8 أرقام بعد المقدمة)', regex='^\\+968\\d{8}$')], verbose_name='رقم الهاتف'),
        ),
    ]
